In [8]:
# Завдання 1

import pandas as pd

df = pd.DataFrame({
    "вік": [19, 24, 31, 37, 42, 48, 53, 27, 61, 35],
    "дохід": [18000, 25000, 32000, 41000, 50000, 58000, 67000, 29000, 75000, 38000],
    "кількість": [1, 2, 3, 2, 4, 1, 3, 2, 5, 2],
    "місто_доставки": [
        "Харків", "Київ", "Львів", "Одеса", "Харків",
        "Дніпро", "Київ", "Полтава", "Львів", "Харків"
    ]
})

df

   вік  дохід  кількість місто_доставки
0   19  18000          1         Харків
1   24  25000          2           Київ
2   31  32000          3          Львів
3   37  41000          2          Одеса
4   42  50000          4         Харків
5   48  58000          1         Дніпро
6   53  67000          3           Київ
7   27  29000          2        Полтава
8   61  75000          5          Львів
9   35  38000          2         Харків

In [9]:
# Завдання 2

base_price = 780

df["сума_замовлення"] = base_price * df["кількість"]
df["частка_доходу"] = df["сума_замовлення"] / df["дохід"]

df

   вік  дохід  кількість місто_доставки  сума_замовлення  частка_доходу
0   19  18000          1         Харків              780       0.043333
1   24  25000          2           Київ             1560       0.062400
2   31  32000          3          Львів             2340       0.073125
3   37  41000          2          Одеса             1560       0.038049
4   42  50000          4         Харків             3120       0.062400
5   48  58000          1         Дніпро              780       0.013448
6   53  67000          3           Київ             2340       0.034925
7   27  29000          2        Полтава             1560       0.053793
8   61  75000          5          Львів             3900       0.052000
9   35  38000          2         Харків             1560       0.041053

In [10]:
# Завдання 3

df["вікова_група_cut"] = pd.cut(
    df["вік"],
    bins=3
)

df["вікова_група_cut"].value_counts().sort_index()

вікова_група_cut
(18.958, 33.0]    4
(33.0, 47.0]      3
(47.0, 61.0]      3
Name: count, dtype: int64

In [11]:

df["вікова_група_qcut"] = pd.qcut(
    df["вік"],
    q=3
)

df["вікова_група_qcut"].value_counts().sort_index()

вікова_група_qcut
(18.999, 31.0]    3
(31.0, 42.0]      3
(42.0, 61.0]      4
Name: count, dtype: int64

In [12]:
# Завдання 4

df["вік_minmax"] = (
    (df["вік"] - df["вік"].min()) /
    (df["вік"].max() - df["вік"].min())
)

df["дохід_minmax"] = (
    (df["дохід"] - df["дохід"].min()) /
    (df["дохід"].max() - df["дохід"].min())
)

df["вік_z"] = (
    (df["вік"] - df["вік"].mean()) /
    df["вік"].std()
)

df["дохід_z"] = (
    (df["дохід"] - df["дохід"].mean()) /
    df["дохід"].std()
)

df[
    [
        "вік",
        "дохід",
        "вік_minmax",
        "дохід_minmax",
        "вік_z",
        "дохід_z"
    ]
].head()

   вік  дохід  вік_minmax  дохід_minmax     вік_z   дохід_z
0   19  18000    0.000000      0.000000 -1.399834 -1.348473
1   24  25000    0.119048      0.122807 -1.025547 -0.975378
2   31  32000    0.285714      0.245614 -0.501545 -0.602283
3   37  41000    0.428571      0.403509 -0.052400 -0.122588
4   42  50000    0.547619      0.561404  0.321887  0.357106

In [13]:
# Завдання 5

city_dummies = pd.get_dummies(
    df["місто_доставки"],
    prefix="місто"
)

df = pd.concat([df, city_dummies], axis=1)

df

,вік,дохід,кількість,місто_доставки,сума_замовлення,частка_доходу,вікова_група_cut,вікова_група_qcut,вік_minmax,дохід_minmax,вік_z,дохід_z,місто_Дніпро,місто_Київ,місто_Львів,місто_Одеса,місто_Полтава,місто_Харків
0,19,18000,1,Харків,780,0.043333,"(18.958, 33.0]","(18.999, 31.0]",0.000000,0.000000,-1.399834,-1.348473,False,False,False,False,False,True
1,24,25000,2,Київ,1560,0.062400,"(18.958, 33.0]","(18.999, 31.0]",0.119048,0.122807,-1.025547,-0.975378,False,True,False,False,False,False
2,31,32000,3,Львів,2340,0.073125,"(18.958, 33.0]","(31.0, 42.0]",0.285714,0.245614,-0.501545,-0.602283,False,False,True,False,False,False
3,37,41000,2,Одеса,1560,0.038049,"(33.0, 47.0]","(31.0, 42.0]",0.428571,0.403509,-0.052400,-0.122588,False,False,False,True,False,False
4,42,50000,4,Харків,3120,0.062400,"(33.0, 47.0]","(42.0, 61.0]",0.547619,0.561404,0.321887,0.357106,False,False,False,False,False,True
5,48,58000,1,Дніпро,780,0.013448,"(47.0, 61.0]","(42.0, 61.0]",0.690476,0.701754,0.771032,0.783500,True,False,False,False,False,False
6,53,67000,3,Київ,2340,0.034925,"(47.0, 61.0]","(42.0, 61.0]",0.809524,0.859649,1.145319,1.263194,False,True,False,False,False,False
7,27,29000,2,Полтава,1560,0.053793,"(18.958, 33.0]","(18.999, 31.0]",0.190476,0.192982,-0.800975,-0.762181,False,False,False,False,True,False
8,61,75000,5,Львів,3900,0.052000,"(47.0, 61.0]","(42.0, 61.0]",1.000000,1.000000,1.744178,1.689589,False,False,True,False,False,False
9,35,38000,2,Харків,1560,0.041053,"(33.0, 47.0]","(31.0, 42.0]",0.380952,0.350877,-0.202115,-0.282486,False,False,False,False,False,True

In [14]:

print("Кількість унікальних міст:", df["місто_доставки"].nunique())
print("Кількість dummy-стовпців:", len(city_dummies.columns))

Кількість унікальних міст: 6
Кількість dummy-стовпців: 6

1. pd.cut() ділить діапазон значень на інтервали приблизно однакової довжини, тому кількість спостережень у групах може бути різною. pd.qcut() формує групи так, щоб у кожній було приблизно однакове число спостережень.

2. Для змінної "місто" використовується one-hot кодування, тому що міста є номінальними категоріями і не мають природного порядку. Кодування міст числами 1, 2, 3 створило б помилкове припущення, що одне місто більше або менше за інше.

3. Масштабування потрібне для того, щоб змінні з різними одиницями та масштабами мали зіставний вплив на методи, чутливі до масштабу. Наприклад, дохід у тисячах гривень має значно більші числові значення, ніж вік.

4. Похідна змінна "частка доходу" показує, яку частину доходу клієнт витратив на замовлення. Вона дозволяє порівнювати клієнтів із різним рівнем доходу, тоді як сама сума замовлення без урахування доходу дає менше інформації про відносне фінансове навантаження.