In [9]:
# Завдання 1

import numpy as np
import pandas as pd

np.random.seed(42)

base_temp = 8.8
amplitude = 15
city = "Харків"

rows = []

for year in [2021, 2022, 2023, 2024]:
    for month in range(1, 13):
        seasonal = amplitude * np.cos((month - 7) / 12 * 2 * np.pi)
        noise = np.random.normal(0, 1.0)

        rows.append({
            "місто": city,
            "рік": year,
            "місяць": month,
            "температура": round(base_temp + seasonal + noise, 1)
        })

climate = pd.DataFrame(rows)

climate

     місто   рік  місяць  температура
0   Харків  2021       1         -5.7
1   Харків  2021       2         -4.3
2   Харків  2021       3          1.9
3   Харків  2021       4         10.3
4   Харків  2021       5         16.1
5   Харків  2021       6         21.6
6   Харків  2021       7         25.4
7   Харків  2021       8         22.6
8   Харків  2021       9         15.8
9   Харків  2021      10          9.3
10  Харків  2021      11          0.8
11  Харків  2021      12         -4.7
12  Харків  2022       1         -6.0
13  Харків  2022       2         -6.1
14  Харків  2022       3         -0.4
15  Харків  2022       4          8.2
16  Харків  2022       5         15.3
17  Харків  2022       6         22.1
18  Харків  2022       7         22.9
19  Харків  2022       8         20.4
20  Харків  2022       9         17.8
21  Харків  2022      10          8.6
22  Харків  2022      11          1.4
23  Харків  2022      12         -5.6
24  Харків  2023       1         -6.7
25  Харків  2023       2         -4.1
26  Харків  2023       3          0.1
27  Харків  2023       4          9.2
28  Харків  2023       5         15.7
29  Харків  2023       6         21.5
30  Харків  2023       7         23.2
31  Харків  2023       8         23.6
32  Харків  2023       9         16.3
33  Харків  2023      10          7.7
34  Харків  2023      11          2.1
35  Харків  2023      12         -5.4
36  Харків  2024       1         -6.0
37  Харків  2024       2         -6.2
38  Харків  2024       3         -0.0
39  Харків  2024       4          9.0
40  Харків  2024       5         17.0
41  Харків  2024       6         22.0
42  Харків  2024       7         23.7
43  Харків  2024       8         21.5
44  Харків  2024       9         14.8
45  Харків  2024      10          8.1
46  Харків  2024      11          0.8
47  Харків  2024      12         -3.1

In [10]:
# Завдання 2

year_stats = climate.groupby("рік")["температура"].agg(
    ["mean", "min", "max"]
)

year_stats

          mean  min   max
рік
2021  9.091667 -5.7  25.4
2022  8.216667 -6.1  22.9
2023  8.600000 -6.7  23.6
2024  8.466667 -6.2  23.7

In [11]:

month_stats = climate.groupby("місяць")["температура"].agg(
    ["mean", "std"]
)

month_stats

          mean       std
місяць
1       -6.100  0.424264
2       -5.175  1.129528
3        0.400  1.023067
4        9.175  0.865544
5       16.025  0.727438
6       21.800  0.294392
7       23.800  1.116542
8       22.025  1.381726
9       16.175  1.250000
10       8.425  0.689807
11       1.275  0.618466
12      -4.700  1.134313

In [12]:


month_stats["std"].idxmax()

np.int64(8)

In [13]:
# Завдання 3

pivot_temp = climate.pivot_table(
    index="місяць",
    columns="рік",
    values="температура",
    aggfunc="mean"
)

pivot_temp

рік     2021  2022  2023  2024
місяць
1       -5.7  -6.0  -6.7  -6.0
2       -4.3  -6.1  -4.1  -6.2
3        1.9  -0.4   0.1   0.0
4       10.3   8.2   9.2   9.0
5       16.1  15.3  15.7  17.0
6       21.6  22.1  21.5  22.0
7       25.4  22.9  23.2  23.7
8       22.6  20.4  23.6  21.5
9       15.8  17.8  16.3  14.8
10       9.3   8.6   7.7   8.1
11       0.8   1.4   2.1   0.8
12      -4.7  -5.6  -5.4  -3.1

In [14]:
# Завдання 4

def get_season(month):
    if month in [12, 1, 2]:
        return "зима"
    elif month in [3, 4, 5]:
        return "весна"
    elif month in [6, 7, 8]:
        return "літо"
    else:
        return "осінь"


climate["сезон"] = climate["місяць"].apply(get_season)

climate["тепліше_за_середнє"] = climate["температура"] > base_temp

climate

     місто   рік  місяць  температура  сезон  тепліше_за_середнє
0   Харків  2021       1         -5.7   зима               False
1   Харків  2021       2         -4.3   зима               False
2   Харків  2021       3          1.9  весна               False
3   Харків  2021       4         10.3  весна                True
4   Харків  2021       5         16.1  весна                True
5   Харків  2021       6         21.6   літо                True
6   Харків  2021       7         25.4   літо                True
7   Харків  2021       8         22.6   літо                True
8   Харків  2021       9         15.8  осінь                True
9   Харків  2021      10          9.3  осінь                True
10  Харків  2021      11          0.8  осінь               False
11  Харків  2021      12         -4.7   зима               False
12  Харків  2022       1         -6.0   зима               False
13  Харків  2022       2         -6.1   зима               False
14  Харків  2022       3         -0.4  весна               False
15  Харків  2022       4          8.2  весна               False
16  Харків  2022       5         15.3  весна                True
17  Харків  2022       6         22.1   літо                True
18  Харків  2022       7         22.9   літо                True
19  Харків  2022       8         20.4   літо                True
20  Харків  2022       9         17.8  осінь                True
21  Харків  2022      10          8.6  осінь               False
22  Харків  2022      11          1.4  осінь               False
23  Харків  2022      12         -5.6   зима               False
24  Харків  2023       1         -6.7   зима               False
25  Харків  2023       2         -4.1   зима               False
26  Харків  2023       3          0.1  весна               False
27  Харків  2023       4          9.2  весна                True
28  Харків  2023       5         15.7  весна                True
29  Харків  2023       6         21.5   літо                True
30  Харків  2023       7         23.2   літо                True
31  Харків  2023       8         23.6   літо                True
32  Харків  2023       9         16.3  осінь                True
33  Харків  2023      10          7.7  осінь               False
34  Харків  2023      11          2.1  осінь               False
35  Харків  2023      12         -5.4   зима               False
36  Харків  2024       1         -6.0   зима               False
37  Харків  2024       2         -6.2   зима               False
38  Харків  2024       3         -0.0  весна               False
39  Харків  2024       4          9.0  весна                True
40  Харків  2024       5         17.0  весна                True
41  Харків  2024       6         22.0   літо                True
42  Харків  2024       7         23.7   літо                True
43  Харків  2024       8         21.5   літо                True
44  Харків  2024       9         14.8  осінь                True
45  Харків  2024      10          8.1  осінь               False
46  Харків  2024      11          0.8  осінь               False
47  Харків  2024      12         -3.1   зима               False

In [15]:


pd.crosstab(
    climate["сезон"],
    climate["тепліше_за_середнє"]
)

тепліше_за_середнє  False  True
сезон
весна                   5      7
зима                   12      0
літо                    0     12
осінь                   7      5

In [16]:
# Завдання 5

pivot_result = climate.pivot(
    index="місяць",
    columns="рік",
    values="температура"
)

pivot_result

рік     2021  2022  2023  2024
місяць
1       -5.7  -6.0  -6.7  -6.0
2       -4.3  -6.1  -4.1  -6.2
3        1.9  -0.4   0.1  -0.0
4       10.3   8.2   9.2   9.0
5       16.1  15.3  15.7  17.0
6       21.6  22.1  21.5  22.0
7       25.4  22.9  23.2  23.7
8       22.6  20.4  23.6  21.5
9       15.8  17.8  16.3  14.8
10       9.3   8.6   7.7   8.1
11       0.8   1.4   2.1   0.8
12      -4.7  -5.6  -5.4  -3.1

1. groupby() працює за принципом split-apply-combine: спочатку дані розділяються на групи за певною ознакою, потім до кожної групи застосовується потрібна операція, а після цього результати об'єднуються в одну таблицю.

2. pivot() працює лише тоді, коли кожній комбінації індексу та стовпця відповідає одне значення. pivot_table() може працювати з дубльованими комбінаціями, тому що додатково агрегує їх за допомогою mean, sum або іншої функції.

3. crosstab() показує частоти комбінацій категоріальних змінних у вигляді таблиці. groupby(...).size() також може рахувати кількість спостережень у групах, але crosstab() зручніше використовувати саме для побудови перехресної таблиці категорій.

4. Довгий tidy-формат зручний для groupby() і pivot_table(), тому що кожне спостереження знаходиться в окремому рядку, а змінні — у стовпцях. Це дозволяє легко групувати, фільтрувати та агрегувати дані без залежності від назв стовпців.