# Практична робота 2
## Робота з DataFrame у Pandas

**Варіант 1 — Київ**

In [7]:
import pandas as pd
months = ["Січ", "Лют", "Бер", "Кві", "Тра", "Чер",
          "Лип", "Сер", "Вер", "Жов", "Лис", "Гру"]

avg_temp = [-4, -3, 2, 9, 15, 19, 21, 20, 14, 8, 2, -2]


precip = [38, 36, 38, 41, 53, 74, 84, 69, 47, 36, 44, 44]

df = pd.DataFrame({
    "month": months,
    "avg_temp": avg_temp,
    "precip": precip
})

df

   month  avg_temp  precip
0    Січ        -4      38
1    Лют        -3      36
2    Бер         2      38
3    Кві         9      41
4    Тра        15      53
5    Чер        19      74
6    Лип        21      84
7    Сер        20      69
8    Вер        14      47
9    Жов         8      36
10   Лис         2      44
11   Гру        -2      44

In [8]:
df.head()

  month  avg_temp  precip
0   Січ        -4      38
1   Лют        -3      36
2   Бер         2      38
3   Кві         9      41
4   Тра        15      53

In [9]:
df.shape

(12, 3)

In [10]:
df.dtypes

month         str
avg_temp    int64
precip      int64
dtype: object

In [11]:
df

   month  avg_temp  precip
0    Січ        -4      38
1    Лют        -3      36
2    Бер         2      38
3    Кві         9      41
4    Тра        15      53
5    Чер        19      74
6    Лип        21      84
7    Сер        20      69
8    Вер        14      47
9    Жов         8      36
10   Лис         2      44
11   Гру        -2      44

In [12]:
df.index

RangeIndex(start=0, stop=12, step=1)

In [13]:
df = df.set_index("month")
df

       avg_temp  precip
month
Січ          -4      38
Лют          -3      36
Бер           2      38
Кві           9      41
Тра          15      53
Чер          19      74
Лип          21      84
Сер          20      69
Вер          14      47
Жов           8      36
Лис           2      44
Гру          -2      44

In [14]:
df.loc["Лип"]

avg_temp    21
precip      84
Name: Лип, dtype: int64

In [15]:
df = df.reset_index()
df

   month  avg_temp  precip
0    Січ        -4      38
1    Лют        -3      36
2    Бер         2      38
3    Кві         9      41
4    Тра        15      53
5    Чер        19      74
6    Лип        21      84
7    Сер        20      69
8    Вер        14      47
9    Жов         8      36
10   Лис         2      44
11   Гру        -2      44

In [16]:
df.index = range(1, 13)
df

   month  avg_temp  precip
1    Січ        -4      38
2    Лют        -3      36
3    Бер         2      38
4    Кві         9      41
5    Тра        15      53
6    Чер        19      74
7    Лип        21      84
8    Сер        20      69
9    Вер        14      47
10   Жов         8      36
11   Лис         2      44
12   Гру        -2      44

In [17]:
df.loc[1:6, "avg_temp"]

1    -4
2    -3
3     2
4     9
5    15
6    19
Name: avg_temp, dtype: int64

In [18]:
df.iloc[0:6, 1]

1    -4
2    -3
3     2
4     9
5    15
6    19
Name: avg_temp, dtype: int64

In [19]:
df[["month", "precip"]]

   month  precip
1    Січ      38
2    Лют      36
3    Бер      38
4    Кві      41
5    Тра      53
6    Чер      74
7    Лип      84
8    Сер      69
9    Вер      47
10   Жов      36
11   Лис      44
12   Гру      44

In [20]:
df[df["avg_temp"] > 15]

  month  avg_temp  precip
6   Чер        19      74
7   Лип        21      84
8   Сер        20      69

In [21]:
df[(df["avg_temp"] > 10) & (df["precip"] > 50)]

  month  avg_temp  precip
5   Тра        15      53
6   Чер        19      74
7   Лип        21      84
8   Сер        20      69

In [22]:
df[(df["avg_temp"] < 0) | (df["precip"] > 80)]

   month  avg_temp  precip
1    Січ        -4      38
2    Лют        -3      36
7    Лип        21      84
12   Гру        -2      44

In [23]:
df["avg_temp_f"] = df["avg_temp"] * 9 / 5 + 32

In [24]:
df

   month  avg_temp  precip  avg_temp_f
1    Січ        -4      38        24.8
2    Лют        -3      36        26.6
3    Бер         2      38        35.6
4    Кві         9      41        48.2
5    Тра        15      53        59.0
6    Чер        19      74        66.2
7    Лип        21      84        69.8
8    Сер        20      69        68.0
9    Вер        14      47        57.2
10   Жов         8      36        46.4
11   Лис         2      44        35.6
12   Гру        -2      44        28.4

In [25]:
df["precip"].mean()

np.float64(50.333333333333336)

In [26]:
df["is_wet"] = df["precip"] > df["precip"].mean()

In [27]:
df

   month  avg_temp  precip  avg_temp_f  is_wet
1    Січ        -4      38        24.8   False
2    Лют        -3      36        26.6   False
3    Бер         2      38        35.6   False
4    Кві         9      41        48.2   False
5    Тра        15      53        59.0    True
6    Чер        19      74        66.2    True
7    Лип        21      84        69.8    True
8    Сер        20      69        68.0    True
9    Вер        14      47        57.2   False
10   Жов         8      36        46.4   False
11   Лис         2      44        35.6   False
12   Гру        -2      44        28.4   False

In [28]:
def get_season(month_number):
    if month_number in [12, 1, 2]:
        return "зима"
    elif month_number in [3, 4, 5]:
        return "весна"
    elif month_number in [6, 7, 8]:
        return "літо"
    else:
        return "осінь"

In [29]:
df["season"] = df.index.to_series().apply(get_season)

In [30]:
df

   month  avg_temp  precip  avg_temp_f  is_wet season
1    Січ        -4      38        24.8   False   зима
2    Лют        -3      36        26.6   False   зима
3    Бер         2      38        35.6   False  весна
4    Кві         9      41        48.2   False  весна
5    Тра        15      53        59.0    True  весна
6    Чер        19      74        66.2    True   літо
7    Лип        21      84        69.8    True   літо
8    Сер        20      69        68.0    True   літо
9    Вер        14      47        57.2   False  осінь
10   Жов         8      36        46.4   False  осінь
11   Лис         2      44        35.6   False  осінь
12   Гру        -2      44        28.4   False   зима

## Письмові відповіді

### 1. Чому `.loc[1:6]` і `.iloc[0:6]` можуть повернути різну кількість рядків?

`.loc` виконує відбір за підписами індексу, а `.iloc` — за позиціями рядків. 
Тому результат залежить від того, які саме значення має індекс DataFrame. 
Крім того, `.loc[1:6]` включає кінцевий підпис 6, а `.iloc[0:6]` не включає позицію 6.

### 2. Чому `and` викликає помилку, а `&` працює?

У Pandas вирази `df["avg_temp"] > 10` та `df["precip"] > 50` повертають цілі серії значень `True` і `False`. 
Оператор `and` призначений для роботи з окремими булевими значеннями, тому для Series він не підходить. 
Оператор `&` виконує поелементне логічне «І», тому його використовують для об'єднання умов у Pandas.

### 3. У чому різниця між формулою та `.apply()`?

Обчислюваний стовпець, створений формулою, виконує одну й ту саму математичну операцію над усіма значеннями стовпця. 
Такий спосіб є векторизованим і зазвичай ефективніший.

`.apply()` дозволяє застосувати власну функцію до кожного значення. 
Його зручно використовувати для складнішої логіки, наприклад для визначення пори року за номером місяця.