Практична №3

In [7]:
import pandas as pd

months = ["Січ", "Лют", "Бер", "Кві", "Тра", "Чер",
          "Лип", "Сер", "Вер", "Жов", "Лис", "Гру"]

cloudiness = [78, 74, 68, 58, 50, 44, 40, 42, 52, 66, 76, 82]

wide = pd.DataFrame({
    "місто": ["Київ"],
    "Січ": [78],
    "Лют": [74],
    "Бер": [68],
    "Кві": [58],
    "Тра": [50],
    "Чер": [44],
    "Лип": [40],
    "Сер": [42],
    "Вер": [52],
    "Жов": [66],
    "Лис": [76],
    "Гру": [82]
})

wide

  місто  Січ  Лют  Бер  Кві  Тра  Чер  Лип  Сер  Вер  Жов  Лис  Гру
0  Київ   78   74   68   58   50   44   40   42   52   66   76   82

In [8]:
wide.shape

(1, 13)

In [9]:
tidy = wide.melt(
    id_vars="місто",
    var_name="місяць",
    value_name="хмарність"
)

tidy

   місто місяць  хмарність
0   Київ    Січ         78
1   Київ    Лют         74
2   Київ    Бер         68
3   Київ    Кві         58
4   Київ    Тра         50
5   Київ    Чер         44
6   Київ    Лип         40
7   Київ    Сер         42
8   Київ    Вер         52
9   Київ    Жов         66
10  Київ    Лис         76
11  Київ    Гру         82

In [10]:
tidy.shape

(12, 3)

місто
Номінальна шкала, тому що назви міст лише позначають категорії і не мають природного порядку.

місяць
У межах цього завдання порядкова шкала, тому що місяці можна розташувати в певному порядку протягом року.

хмарність
Шкала відношень, тому що це кількісна величина у відсотках, для якої існує природний нуль і можна порівнювати відношення значень.

In [11]:
back = tidy.pivot(
    index="місто",
    columns="місяць",
    values="хмарність"
)

back

місяць  Бер  Вер  Гру  Жов  Кві  Лип  Лис  Лют  Сер  Січ  Тра  Чер
місто
Київ     68   52   82   66   58   40   76   74   42   78   50   44

In [12]:
back.shape

(1, 12)

In [13]:
tidy.to_csv("variant.csv", index=False)

In [14]:
tidy.to_json(
    "variant.json",
    orient="records",
    force_ascii=False
)

In [15]:
reloaded_csv = pd.read_csv("variant.csv")
reloaded_csv

   місто місяць  хмарність
0   Київ    Січ         78
1   Київ    Лют         74
2   Київ    Бер         68
3   Київ    Кві         58
4   Київ    Тра         50
5   Київ    Чер         44
6   Київ    Лип         40
7   Київ    Сер         42
8   Київ    Вер         52
9   Київ    Жов         66
10  Київ    Лис         76
11  Київ    Гру         82

In [16]:
reloaded_json = pd.read_json("variant.json")
reloaded_json

   місто місяць  хмарність
0   Київ    Січ         78
1   Київ    Лют         74
2   Київ    Бер         68
3   Київ    Кві         58
4   Київ    Тра         50
5   Київ    Чер         44
6   Київ    Лип         40
7   Київ    Сер         42
8   Київ    Вер         52
9   Київ    Жов         66
10  Київ    Лис         76
11  Київ    Гру         82

In [17]:
tidy.equals(reloaded_csv)

True

In [18]:
tidy.equals(reloaded_json)

True

In [19]:
print(open("variant.csv", encoding="utf-8").read())

місто,місяць,хмарність
Київ,Січ,78
Київ,Лют,74
Київ,Бер,68
Київ,Кві,58
Київ,Тра,50
Київ,Чер,44
Київ,Лип,40
Київ,Сер,42
Київ,Вер,52
Київ,Жов,66
Київ,Лис,76
Київ,Гру,82

In [20]:
print(open("variant.json", encoding="utf-8").read())

[{"місто":"Київ","місяць":"Січ","хмарність":78},{"місто":"Київ","місяць":"Лют","хмарність":74},{"місто":"Київ","місяць":"Бер","хмарність":68},{"місто":"Київ","місяць":"Кві","хмарність":58},{"місто":"Київ","місяць":"Тра","хмарність":50},{"місто":"Київ","місяць":"Чер","хмарність":44},{"місто":"Київ","місяць":"Лип","хмарність":40},{"місто":"Київ","місяць":"Сер","хмарність":42},{"місто":"Київ","місяць":"Вер","хмарність":52},{"місто":"Київ","місяць":"Жов","хмарність":66},{"місто":"Київ","місяць":"Лис","хмарність":76},{"місто":"Київ","місяць":"Гру","хмарність":82}]

# Письмові відповіді

### 1. Чому стовпець «місто» — номінальна шкала, а «хмарність» — шкала відношень?

Стовпець «місто» має номінальну шкалу, тому що назви міст є категоріями, між якими немає числового порядку або значення «більше/менше». Стовпець «хмарність» має шкалу відношень, тому що це кількісна величина у відсотках, яка має природний нуль (0%) і для якої можна порівнювати відношення значень.

### 2. Чому wide-таблиця з місяцями в стовпцях не є tidy?

У wide-таблиці кожен місяць є окремим стовпцем, тому одна змінна «місяць» фактично розподілена між багатьма назвами стовпців. Після застосування `melt()` назви місяців перетворюються на значення одного стовпця «місяць», а значення хмарності — на стовпець «хмарність». У результаті кожен місяць представлений окремим рядком.

### 3. Чим CSV відрізняється від JSON?

CSV зберігає інформацію у вигляді таблиці: рядки складаються зі значень, розділених спеціальним символом, наприклад комою. JSON зберігає дані у структурі об'єктів і масивів та може краще представляти складні або вкладені дані. Для цієї таблиці обидва формати дозволяють зберегти однакову інформацію, але записують її по-різному.